### ISSUE TITLE
Name output file using only test codes

### ISSUE THREAD

**Issue by sophie22** [eastgenomics/eggd_generate_bed#23]
In the [dias_cnvreports](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/blob/main/dxworkflow.json) workflow at the [eggd_annotate_excluded_regions](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/main/resources/home/dnanexus/annotate_excluded_panel.py)  stage, the linked Python script errors out if the input filename is too many characters.
The input bed file to eggd_annotate_excluded_regions is the output file from eggd_generate_bed.

**Comment by jethror1** [comment]
you can set the output bed file name with `output_file_prefix`, doesn't that handle this?

**Comment by sophie22** [comment]
I didn't know or check that this is an option. The solution may then be to provide this optional prefix input to the app when setting off the workflow.
Closing this issue and opening one on dias_batch_running to provide this output_prefix string as input to generate_bed app stages.
